### ISSUE TITLE
Option for spacing link origins

### ISSUE THREAD

**Issue by dominicfollett** [skieffer/hola#10]
@skieffer Is there an option that allows you to space the originating/terminating position for a link?

E.g. 

<img width="722" alt="screenshot 2018-11-26 at 10 55 31" src="https://user-images.githubusercontent.com/9007502/49003141-06571d80-f16a-11e8-8dc6-1ccc36f9a8a8.png">

For node 10, I'd like those links to be spaced further apart across more of the box's real estate.

I'm using your fork of Adaptagrams C++ library.

**Comment by skieffer** [comment]
For the final routing, HOLA uses a `Router`, from `libavoid`. This has a parameter called `idealNudgingDistance` that would control the spacing you want. At present there's no way to set that parameter in the `Router` that HOLA uses, so you'd have to hack it. Look somewhere around line `410` in `hola.cpp`. I think the default value is 4 (pixels), so try setting something a bit larger. Might look something like this:

    ra.router.setRoutingParameter(Avoid::idealNudgingDistance, 8);

**Comment by dominicfollett** [comment]
Gotcha, thanks! Maybe I can submit a PR once your fork is merged.
