### ISSUE TITLE
big graph problem

### ISSUE THREAD

**Issue by zhuyali** [skieffer/hola#7]
Now we have more than 2000 points, and when we run this program, we find it fails. So we want to know if this program supports graph has so many points ?

**Comment by skieffer** [comment]
_In theory_ the algorithm could work on graphs of any size, but generally speaking we have found an upper limit of about one to two hundred nodes in practice, for the algorithm to complete in reasonable time and give a decent result.

In the future we hope to release a C++ version of the algorithm, which may perhaps scale better, but the release date for that is not set yet.
